name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install devDependencies
        run: yarn add --dev @babel/plugin-proposal-private-property-in-object
      - name: Build app
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn build
      - name: Deploy app
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
