name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Install devDependencies
        run: npm install --only=dev
      - name: Add missing dependency
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
      - name: Build app
        run: npm run build
      - name: Deploy app
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build